### ISSUE TITLE
Glib Error

### ISSUE THREAD

**Issue by TbagSqueezer** [leebaird/discover#36] opened 2016-01-05 21:53 UTC
Getting a ton of errors on a new Kali 2.0 install.
- Did GIT pull
- Did update.sh
- Ran the Recon -> Domain -> Passive (#1, #1)
- The scan completes but many files are missing from the report web page like Netcraft and config etc..

********************
Scan starts fine then gets to the below:
********************
Press <return> to continue.

(process:36574): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
console.error: 
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node
console.error: 
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node

(process:36613): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
...
...
...
(process:37494): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
(process:37499): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

**Comment by L1ghtn1ng** [comment] 2016-01-05 23:06
Hi, can you please paste the entire output of what you are doing please, thanks

Date: Tue, 5 Jan 2016 13:53:23 -0800

**Comment by TbagSqueezer** [comment] 2016-01-06 03:47
Here is the full capture.

root@DLCkali:/opt/discover# ./discover.sh 

______  ___ ______ ______  _____  _    _ ______  _____
|     \  |  |____  |      |     |  \  /  |_____ |____/
|_____/ _|_ _____| |_____ |_____|   \/   |_____ |    \_

By Lee Baird


RECON
1.  Domain
2.  Person
3.  Parse salesforce

SCANNING
4.  Generate target list
5.  CIDR
6.  List
7.  IP, Range or URL

WEB
8.  Open multiple tabs in Firefox
9.  Nikto
10. SSL

MISC
11. Crack WiFi
12. Parse XML
13. Start a Metasploit listener
14. Update
15. Exit

Choice: 1


______  ___ ______ ______  _____  _    _ ______  _____
|     \  |  |____  |      |     |  \  /  |_____ |____/
|_____/ _|_ _____| |_____ |_____|   \/   |_____ |    \_

By Lee Baird


RECON

1.  Passive
2.  Active
3.  Previous menu

Choice: 1

=====================================================================================

Usage

Company: Target
Domain:  target.com

=====================================================================================

Company: Target
Domain:  target.com

=====================================================================================

dnsrecon                  (1/26)

goofile                   (2/26)

goog-mail                 (3/26)

goohost
     IP                   (4/26)
     Email                (5/26)

theHarvester
     Baidu                (6/26)
     Bing                 (7/26)
     Dogpilesearch        (8/26)
     Google               (9/26)
     Google CSE           (10/26)
     Google+              (11/26)
     Google Profiles	  (12/26)
     Jigsaw               (13/26)
     LinkedIn             (14/26)
     People123            (15/26)
     PGP                  (16/26)
     Yahoo                (17/26)
     All                  (18/26)

Metasploit                (19/26)

URLCrazy                  (20/26)

Whois
     Domain               (21/26)
     IP 		  (22/26)

dnssy.com                 (23/26)
ewhois.com                (24/26)
myipneighbors.net         (25/26)
urlvoid.com               (26/26)

=====================================================================================

***Scan complete.***


The supporting data folder is located at /root/data/Target.com/

Press <return> to continue.

(process:36574): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
console.error: 
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node
console.error: 
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node

(process:36613): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(process:36627): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(process:36632): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(process:36638): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(process:36643): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(process:36648): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(process:36653): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(process:36659): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(process:36672): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(process:36677): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(process:36683): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(process:36688): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(process:36693): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(process:36698): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed


root@DLCkali:/opt/discover# 
(process:36703): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

**Comment by jayw0k** [comment] 2016-01-06 05:45
This is a Mozilla bug, not Discover.  Iceweasel should still launch & display all tabs correctly though.

**Comment by TbagSqueezer** [comment] 2016-01-06 05:57
Yeah the tabs are opening fine. I'll work with just the tabs, thanks.

**Comment by c00lnc0llected** [comment] 2016-01-09 18:52
I'm seeing the same issue and the results display fine in Iceweasel.  However, the problem is that the directory is not created in /root/data so once the browser is closed I have to run the discover script again to get the results.

**Comment by c00lnc0llected** [comment] 2016-01-09 19:33
Below is the full capture of what happens when I run the ./discover.sh script from /opt/discover


______  ___ ______ ______  _____  _    _ ______  _____
|     \  |  |____  |      |     |  \  /  |_____ |____/
|_____/ _|_ _____| |_____ |_____|   \/   |_____ |    \_

By Lee Baird


RECON
1.  Domain
2.  Person
3.  Parse salesforce

SCANNING
4.  Generate target list
5.  CIDR
6.  List
7.  IP, Range or URL

WEB
8.  Open multiple tabs in Firefox
9.  Nikto
10. SSL

MISC
11. Crack WiFi
12. Parse XML
13. Start a Metasploit listener
14. Update
15. Exit

Choice: 1



______  ___ ______ ______  _____  _    _ ______  _____
|     \  |  |____  |      |     |  \  /  |_____ |____/
|_____/ _|_ _____| |_____ |_____|   \/   |_____ |    \_

By Lee Baird


RECON

1.  Passive
2.  Active
3.  Previous menu

Choice: 1


=====================================================================================

Usage

Company: Target
Domain:  target.com

=====================================================================================

Company: Target
Domain:  target.com

cp: target ‘/root/data/target.com’ is not a directory
sed: can't read /root/data/target.com/index.htm: No such file or directory
mv: cannot move ‘tmp’ to ‘/root/data/target.com/index.htm’: No such file or directory

=====================================================================================

dnsrecon                  (1/26)

goofile                   (2/26)

goog-mail                 (3/26)
./discover.sh: line 210: /opt/discover: Is a directory

goohost
     IP                   (4/26)
./discover.sh: line 222: /opt/discover: Is a directory
     Email                (5/26)
./discover.sh: line 224: /opt/discover: Is a directory
cat: report-*: No such file or directory
rm: cannot remove ‘*-target.com.txt’: No such file or directory

theHarvester
     Baidu                (6/26)
     Bing                 (7/26)
     Dogpilesearch        (8/26)
     Google               (9/26)
     Google CSE           (10/26)
     Google+              (11/26)
     Google Profiles	  (12/26)
     Jigsaw               (13/26)
     LinkedIn             (14/26)
     People123            (15/26)
     PGP                  (16/26)
     Yahoo                (17/26)
     All                  (18/26)

Metasploit                (19/26)

URLCrazy                  (20/26)

Whois
     Domain               (21/26)
     IP 		  (22/26)

dnssy.com                 (23/26)
./discover.sh: line 422: /root/data/target.com/data/config.htm: No such file or directory
ewhois.com                (24/26)
myipneighbors.net         (25/26)
urlvoid.com               (26/26)
./discover.sh: line 438: /root/data/target.com/data/black-listed.htm: No such file or directory
./discover.sh: line 442: /root/data/target.com/data/hosts.htm: No such file or directory
./discover.sh: line 442: /root/data/target.com/data/hosts.htm: No such file or directory
./discover.sh: line 461: /root/data/target.com/data/emails.htm: No such file or directory
./discover.sh: line 490: /root/data/target.com/data/squatting.htm: No such file or directory
./discover.sh: line 500: /root/data/target.com/data/subdomains.htm: No such file or directory
./discover.sh: line 562: /root/data/target.com/data/emails.htm: No such file or directory
./discover.sh: line 563: /root/data/target.com/data/names.htm: No such file or directory
./discover.sh: line 564: /root/data/target.com/data/squatting.htm: No such file or directory
./discover.sh: line 565: /root/data/target.com/data/subdomains.htm: No such file or directory
./discover.sh: line 566: /root/data/target.com/data/whois-domain.htm: No such file or directory
./discover.sh: line 566: /root/data/target.com/data/whois-domain.htm: No such file or directory
./discover.sh: line 567: /root/data/target.com/data/whois-ip.htm: No such file or directory
./discover.sh: line 567: /root/data/target.com/data/whois-ip.htm: No such file or directory
./discover.sh: line 568: /root/data/target.com/data/passive-recon.htm: No such file or directory
./discover.sh: line 568: /root/data/target.com/data/passive-recon.htm: No such file or directory

=====================================================================================

***Scan complete.***


The supporting data folder is located at /root/data/target.com/

Press <return> to continue.


When I press <return>, the results open in Iceweasel, however, the results are not saved to the /root/data/[domain] directory.

**Comment by L1ghtn1ng** [comment] 2016-01-09 19:39
Please can you try having the name all lower case for the company name
and see if that works?

**Comment by jayw0k** [comment] 2016-01-09 21:37
You likely have discover.sh in an additional path, which is being grabbed instead of /opt/discover/

Do the following:
 `locate discover.sh` 
Remove discover.sh from all paths except /opt/discover/
 If you need a separate copy, it will need to be renamed (ex. discover-copy.sh) to not conflict with Discover validating its path
` updatedb`

Run Discover again & report back on your results

**Comment by L1ghtn1ng** [comment] 2016-01-09 21:47
@jayw0k That could be the case, but I have come across this issue before and did discuss it with Lee. It was a while ago now so I cannot remember exactly what he said about the issue @c00lnc0llected is having. If I recall correctly as I stated previously try it with lower case words and make sure there are no spaces as well. I will look in to it again

**Comment by jayw0k** [comment] 2016-01-09 21:56
Yeah, that wasn't directed at your comment, just an additional suggestion w/ reference to a previous issue.

**Comment by L1ghtn1ng** [comment] 2016-01-09 22:04
@jayw0k Fair enough

**Comment by L1ghtn1ng** [comment] 2016-01-09 23:16
@c00lnc0llected I cannot seem to reproduce it. Are you using the latest version from master?

**Comment by leebaird** [comment] 2016-01-10 19:17
As jaywalk mentioned, this is a know bug with Firefox. Sometimes the browser with hang on a particular tab, causing additional tabs to fail to open. I have found that before I run the Discover recon modules I open the browser from the command line first, then close it. That seems to produce more consistent results.

**Closed** 2016-01-10 19:17 UTC

**Comment by c00lnc0llected** [comment] 2016-01-11 14:21
I'm getting the same errors even when I type in the company name in all lowercase.  Is there a fix for this?  

Thank you.
 

    On Sunday, January 10, 2016 2:17 PM, Lee Baird <notifications@github.com> wrote:
 

 Closed #36.—

**Comment by c00lnc0llected** [comment] 2016-01-11 15:07
I'm running the latest master version.  I'm also running it from /opt/discover.  I have it installed on Kali Linux 2.0.  Not sure if that's an issue.  I'm experiencing this every time I run it.  Strange...

**Comment by jayw0k** [comment] 2016-01-12 00:26
Can you confirm that discover.sh is only located in /opt/discover/ ?
If you get more than that result, it will need to be removed or renamed in all other locations.  See my note above for further details.

**Comment by c00lnc0llected** [comment] 2016-01-12 13:35
Yes, the discover.sh script is located in the /opt/discover directory.  I didn't change anything after installing this tool.
Thank you.
 

    On Monday, January 11, 2016 7:26 PM, Jason Ashton <notifications@github.com> wrote:
 

 Can you confirm that discover.sh is only located in /opt/discover/ ?
If you get more than that result, it will need to be removed or renamed in all other locations. See my note above for further details.—

**Comment by jayw0k** [comment] 2016-01-12 14:11
Can you run `updatedb`, then `locate discover.sh` & paste your output

**Comment by L1ghtn1ng** [comment] 2016-01-13 13:30
@c00lnc0llected Have you been able to do what @jayw0k has suggested? If you have and you do not have 2 copies of discover. Is it possible if this is a VM you are using and having this issue in able to upload the VM so we could get a good look at what is going on? I will create another VM and see if I can reproduce it, but having no such luck at this time.
