### ISSUE TITLE
 theharvester stop searching when he switched to Baidu

### ISSUE THREAD

**Issue by blbecmatej** [leebaird/discover#92] opened 2017-02-02 13:39 UTC
Hi lee,

i love this tool, but I have a problem with theHarvester, when he starts looking through Baidu, so he stops and does not continue beyond. When I pause the search and run again passive gathering, so sometimes happens that suddenly come through normally. viz screen shot below.
Please do not know what it could be?

Thanks a lot.

![screenshot from 2017-02-02 10-58-23](https://cloud.githubusercontent.com/assets/25502434/22546981/b078a318-e93f-11e6-981f-9245de90500a.png)

**Comment by L1ghtn1ng** [comment] 2017-02-03 19:13
Thanks for the report, will see if I can reproduce the issue

________________________________

**Comment by L1ghtn1ng** [comment] 2017-02-06 18:42
Due to illness this will take a little bit before I can have a look at this

________________________________

**Comment by leebaird** [comment] 2017-03-10 19:46
I can't reproduce this bug. Scan are working fine for me on multiple VMs and locations.
I'm closing the ticket.

**Closed by leebaird** 2017-03-10 19:46 UTC

**Comment by L1ghtn1ng** [comment] 2017-03-10 20:19
Will see if I can reproduce this, sorry I have taken so long was I'll then having dealing with work related stress. Will check when I get home

Sent from phone


________________________________

**Comment by leebaird** [comment] 2017-03-10 21:43
It's ok

--

Lee
615-293-7625

**Comment by L1ghtn1ng** [comment] 2017-03-11 01:42
I cannot reproduce this either
